packages:
  - "flippo-backend"
  - "flippo-frontend"
  - "packages/*"
catalog:
  "@antfu/eslint-config": ^4.11.0
  "@eslint-react/eslint-plugin": ^1.40.3
  eslint: ^9.23.0
  eslint-plugin-format: ^1.0.1
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.19
  eslint-plugin-turbo: ^2.5.0
  jiti: ^2.4.2
  typescript: ^5.8.2
