packages:
  - "backend"
  - "frontend"
  - "packages/*"
  - "packages/ui/*"

catalog:
  "@antfu/eslint-config": ^4.11.0
  "@biomejs/biome": "2.0.0-beta.1"
  "@chromatic-com/storybook": 3.2.6
  "@eslint-react/eslint-plugin": ^1.40.3
  "@farfetched/core": ^0.13.1
  "@figma-export/core": ^6.2.0
  "@storybook/addon-essentials": 8.6.11
  "@storybook/addon-interactions": 8.6.11
  "@storybook/addon-onboarding": 8.6.11
  "@storybook/blocks": 8.6.11
  "@storybook/manager-api": ^8.6.11
  "@storybook/react": 8.6.11
  "@storybook/react-vite": 8.6.11
  "@storybook/test": 8.6.11
  "@storybook/theming": ^8.6.11
  "@svgr/core": ^8.1.0
  "@svgr/plugin-jsx": ^8.1.0
  "@testing-library/webdriverio": ^3.2.1
  "@testplane/global-hook": ^1.0.0
  "@testplane/storybook": ^1.6.1
  "@testplane/test-filter": ^1.0.0
  "@testplane/url-decorator": ^1.0.0
  "@turbo/gen": ^2.4.4
  "@types/eslint": ^9.6.1
  "@types/js-cookie": ^3.0.6
  "@types/node": ^22.14.0
  "@types/react": 19.0.12
  "@types/react-dom": 19.0.4
  "@vitejs/plugin-react": ^4.3.4
  "@withease/i18next": ^24.0.0
  "@withease/web-api": ^1.3.0
  atomic-router: ^0.11.0
  atomic-router-react: ^0.10.0
  axios: ^1.8.4
  clsx: ^2.1.1
  effector: ^23.3.0
  effector-react: ^23.3.0
  esbuild: ^0.25.2
  eslint: ^9.24.0
  eslint-plugin-effector: ^0.15.0
  eslint-plugin-format: ^1.0.1
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.19
  eslint-plugin-storybook: ^0.12.0
  eslint-plugin-turbo: ^2.5.0
  framer-motion: ^12.6.2
  globals: ^16.0.0
  history: ^5.3.0
  html-reporter: ^10.15.0
  i18next: ^24.2.3
  i18next-browser-languagedetector: ^8.0.4
  i18next-hmr: ^3.1.3
  i18next-http-backend: ^3.0.2
  is-svg: ^5.1.0
  jiti: ^2.4.2
  js-cookie: ^3.0.5
  patronum: ^2.3.0
  postcss: ^8.5.3
  postcss-flexbugs-fixes: ^5.0.2
  postcss-preset-env: ^10.1.5
  react-i18next: ^15.4.1
  react-use-measure: ^2.1.7
  sass-embedded: ^1.86.1
  storybook: 8.6.11
  storybook-react-i18next: ^3.2.1
  stylelint: ^16.17.0
  surrealdb: ^1.2.1
  svgo: ^3.3.2
  testplane: ^8.26.0
  tsup: ^8.4.0
  typescript: ^5.8.2
  react: "^19.1.0"
  "react-dom": "^19.1.0"
  vite: ^6.2.4
  vite-plugin-dts: ^4.5.3
  zod: ^3.24.2
